export {default as Homepage} from './Homepage/Homepage';
export {default as Phones} from './Phones/Phones';
export {default as Tablets} from './Tablets';
export {default as Accessories} from './Accessories/Accessories';
export {default as Cart} from './Cart';
export {default as Favorites} from './Favorites';
export {default as NotFound} from './NotFound';
export {default as ProductDetailsPage} from './ProductDetailsPage/ProductDetailsPage';
export {default as ProductPage} from './ProductPage/ProductPage';
